### ISSUE TITLE
Hardcoded contact emails

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-teams#10]
Various pages in Teams have hardcoded contact endpoints for support, 

See:
https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/webapp/WEB-INF/tags/genericpage.tag#L90

https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/webapp/error.jsp#L83

https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/resources/ftl/macros_htmlmail.ftl#L94

https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/resources/ftl/macros_plaintextmail.ftl#L22

**Comment by lvonk** [comment]
When does this need to differ? By language?

**Comment by thijskh** [comment]
No, it needs to be configurable in case you are a different organization than SURFnet and want to run Teams. You want to be able to configure your own contact info and not have your users contact SURFnet.

**Comment by lvonk** [comment]
Ok. @surfnet-niels There are many more context dependent references that are hardcoded (like logos, titles, link names). Do you need it for something specific?

**Comment by thijskh** [comment]
New issue put on [OpenConext-Teams-NG](/OpenConext/OpenConext-Teams-NG) backlog.
