### ISSUE TITLE
Hardcoded references to SURFconext wiki pages

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-teams#11]
Various pages in Teams have hardcoded references to SURFconext wiki pages

See:
https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/webapp/WEB-INF/tags/genericpage.tag

https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/webapp/error.jsp

https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/resources/ftl/macros_htmlmail.ftl

https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/resources/ftl/macros_plaintextmail.ftl

**Comment by lvonk** [comment]
When does this need to differ? By language?

**Comment by thijskh** [comment]
No, it needs to be configurable in case you are a different organization than SURFnet and want to run Teams. You want to be able to configure your own documentation URLs.

**Comment by lvonk** [comment]
Ok. @surfnet-niels There are many more context dependent references that are hardcoded (like logos, titles, link names). Do you need it for something specific?

**Comment by surfnet-niels** [comment]
Initially I would consider everything that is in CSS as configurable. Optionally we could make the location of the CSS itself a config param:
https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/webapp/WEB-INF/tags/genericpage.tag#L36 and https://github.com/OpenConext/OpenConext-teams/blob/master/coin-teams-war/src/main/webapp/WEB-INF/tags/genericpage.tag#L38

Most of the stuff in pages mentioned above is hardcoded contact data which should be in the config files I think.
The logo could be in CSS, not hardcoded into the pages

**Comment by thijskh** [comment]
New issue on [OpenConext-Teams-NG](/OpenConext/OpenConext-Teams-NG) backlog.
