### ISSUE TITLE
Changing roles in Teams is not working

### ISSUE THREAD

**Issue by femke** [OpenConext/OpenConext-teams#13]
When you try to remove the 'admin-role' of a user, you un-check the checkmark, but the result is a message: 'Role was added' and the checkmark back in place
![error1](https://cloud.githubusercontent.com/assets/1846679/6263944/b0887cba-b81e-11e4-813f-1a8c371bfc7d.png)

When you try to assign the 'admin-role' to a user, you check the box, but the result is the message: 'No role removed, there must be always one admin' and the box is unchecked.
![error2](https://cloud.githubusercontent.com/assets/1846679/6263943/b06bd088-b81e-11e4-86c4-989f93728c97.png)

This one is taken at the second attempt to check the box. You can still the 'Role was Removed' message. And while it seems possible to check a box, this the screen wil update with 'Role was Removed' and an empty box again.
![error3](https://cloud.githubusercontent.com/assets/1846679/6263942/b051b3c4-b81e-11e4-9c8c-7c783310da2f.png)

Thus, it delivers no error messages but just doesn't respond correctly to the user input. For users it is very confusing since it seems able to check / uncheck boxes. This test was executed in Firefox / Chrome / Safari / IE with the same results.

**Comment by hanswesterbeek** [comment]
actual PR at https://github.com/OpenConext/OpenConext-teams/pull/14

**Comment by hanswesterbeek** [comment]
Fixed in 4.0.1.4 which will appear on Acc shortly.
