### ISSUE TITLE
emails sent bij teams contain remote content

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-teams#16]
Mail sent by SURFteams contains a remotely reference SURFconext logo:

![screen shot 2015-08-11 at 10 55 21](https://cloud.githubusercontent.com/assets/1461740/9193909/7ba65ff4-4017-11e5-9d55-b154e99d3f52.png)

This should be replaced by a properly attached logo and internal reference.

**Comment by thijskh** [comment]
Or what about just no logo?

**Comment by baszoetekouw** [comment]
+1

**Comment by baszoetekouw** [comment]
:cry: 
:princess: 
:smirk_cat:

**Comment by arnoutt** [comment]
I'd be happy thoroughly review this invitation email (again) and see if we can improve more stuff.
