### ISSUE TITLE
Can't see which identity of a user is part of my team

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-teams#17]
The list of members of my team shows full names and email addresses. But there's no way for me to see the actual identity (`urn:collab:person:`whatever). This can be relevant information however, for example to know with which IdP the user has accepted the invite.

Maybe too detailed for joe average user, but something like a tooltip where powerusers can find it, might be a good compromise.

**Comment by arnoutt** [comment]
Should one be able to copy this identifier? A 'simple' tooltip can show the identifier but the text is not selectable.

Of course we could go for a more advanced tooltip but that will take more time.

**Comment by thijskh** [comment]
Showing it is enough for my use case. I have a team with twice the same fullname in it. I cannot see which one is from which IdP.

**Comment by thijskh** [comment]
I think the tooltip is enough in general. It should not be necessary to copy person id's out of teams.

**Comment by arnoutt** [comment]
Ok, thanks.

**Comment by alanvdam** [comment]
Resolved by b284b1d0ebcb2c611eeabc7f738466900bdaa785
