### ISSUE TITLE
Use isMemberOf attribute to determine guest status

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-teams#18]
Teams discerns between 'guests' and 'members'. Only the latter can create teams and become an admin of existing teams. Current (4.0.x) teams uses a call to OpenConext API to determine this.

We would like teams to use the isMemberOf attribute that it would get from Shibboleth instead. If this attribute contains a specific value (in our case `urn:collab:org:surf.nl`) the user is a member. If the attribute has any other value or is absent, the user is a guest.

**Comment by oharsta** [comment]
Implemented in 2c45b6fb612333598b914b86262721c2526d2efe
