### ISSUE TITLE
I want to see the identifier of my teams

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-teams#19]
A Team can be used by IdP's and/or SP's to make authorisation decisions, e.g. 'members of team XYZ are allowed to login to service ABC'. To configure this AuthZ decision, the IdP or SP manager must know the unique identifier of the Team.

This is currently not visible to end users.

**Comment by alanvdam** [comment]
Resolved by 96d6cf8739cfeb44620fcd87fc9137e74f8296fe
