### ISSUE TITLE
Send Again throws error

### ISSUE THREAD

**Issue by surfnet-niels** [OpenConext/OpenConext-teams#20]
When I want to send a team invite again using "Send Again" selecting the link leads to an error in Teams, see screenshot
![screen shot 2015-11-10 at 09 49 36](https://cloud.githubusercontent.com/assets/1491826/11058297/2ee9ef7e-8792-11e5-9cc4-65237174b031.png)
![screen shot 2015-11-10 at 09 48 34](https://cloud.githubusercontent.com/assets/1491826/11058300/31db81d4-8792-11e5-9e1a-40023d6f84a9.png)

**Comment by thijskh** [comment]
This was not specific to send again but a side effect from spring boot storing compliled template files under /tmp which were cleared out after a few weeks by a tmpcleaning script. This has been fixed by changing the file storage location of the application.
