### ISSUE TITLE
Display full unique identifier for external groups

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-teams#22]
When an institution's external group provider is connected through VOOT, a user can see which (external) groups he is a member of. However, the unique ID for those groups is nowhere to be found.

It would be nice if the table with external groups gets another column (after name, before description) where this unique ID is displayed.

Note: I'm referring to the full unique identifier: urn:collab:group:institution:groupname

**Comment by thijskh** [comment]
Solved in [OpenConext-Teams-NG](/OpenConext/OpenConext-Teams-NG).
