### ISSUE TITLE
Team names (and ids!) with weird characters should not be allowed

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-teams#23]
Teams allows all kinds of weird characters in team names, such as "[]%&^#|
This wouldn't be so bad, if the team name wasn't (almost) exactly used in the urn:-identifier.

The current situation leads to team identifiers like this (VOOT output below):

```
"id" : "urn:collab:group:surfteams.nl:nl:surfnet:diensten:____;"
"id" : "urn:collab:group:surfteams.nl:nl:surfnet:diensten:'"
"id" : "urn:collab:group:surfteams.nl:nl:surfnet:diensten:hallo';show_tables;_leuk_zeg!"
"id" : "urn:collab:group:surfteams.nl:nl:surfnet:diensten:trust_&_identity_2015"
"id" : "urn:collab:group:surfteams.nl:nl:surfnet:diensten:`~!@#$^&()))))__+-={}|[];'\".?"
```

Note that URNs can only consist of the following caracters (as defined in section 2.2 of https://tools.ietf.org/html/rfc2141:

```
   <NSS>         ::= 1*<URN chars>

   <URN chars>   ::= <trans> | "%" <hex> <hex>

   <trans>       ::= <upper> | <lower> | <number> | <other> | <reserved>

   <hex>         ::= <number> | "A" | "B" | "C" | "D" | "E" | "F" |
                     "a" | "b" | "c" | "d" | "e" | "f"

   <other>       ::= "(" | ")" | "+" | "," | "-" | "." |
                     ":" | "=" | "@" | ";" | "$" |
                     "_" | "!" | "*" | "'"
```

The best way to fix this, would probably be to just hex-encode any chars other than the ones mentioned above.  That would also allow a nice way to fix the ambiguity issues with spaces-to-underscore translations (simply encoding spaces as %20 in the id) and with missing control chars like `:<>%`.

Apart from these technical issues, it might also be useful to enforce team name conventions like (for example:
- minimum length for team name
- team name must contain a minimum jumber of letters
- team names must start with a letters

**Comment by thijskh** [comment]
Solved in [OpenConext-Teams-NG](/OpenConext/OpenConext-Teams-NG).
