### ISSUE TITLE
Internationalized team names

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-teams#24]
Currently, team names seem to be limited to US-ASCII (or maybe iso8859-15 or some such legacy charset).  Trying to make the Begnali team `চীনত বিশ্বৰ জনসংখ্যাৰ`, results in the following team:

``` json
{
  "id" : "urn:collab:group:surfteams.nl:nl:surfnet:diensten:????_??????_?????????",
  "displayName" : "???? ?????? ?????????",
  "description" : "",
  "sourceID" : "SURFteams",
  "membership" : {
    "basic" : "member"
  }
}
```

Section 2.2 of  https://tools.ietf.org/html/rfc2141 describes how to encode unicode in URNs (hex-encoded UTF-8).

**Comment by thijskh** [comment]
Solved in [OpenConext-Teams-NG](/OpenConext/OpenConext-Teams-NG).
