### ISSUE TITLE
Group consent is never actually checked

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-teams#25]
When creating a team, one is suppoed to give consent for sharing group info.  However, this "check: seems only to be implemented by making the "create" button active.  There is no server side check, so the consent check is easy to circumvent.

One way would be to manually change the DOM structure in the browser.  Another one is by triggering an error in teams (for example, by creating a team named `<>`) and pressing "back" in the browser.

**Comment by thijskh** [comment]
Solved in [OpenConext-Teams-NG](/OpenConext/OpenConext-Teams-NG).
