### ISSUE TITLE
Shows stack traces when displayName or schacHomeOrganization are missing

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-teams#28]
The LDAP provisioning code makes use of displayName and schacHomeOrganization. If either of these is somehow not provided, an exception about incwith stack traces is thrown in the user's face:

`org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.ldap.InvalidAttributeValueException: [LDAP: error code 21 - sn: value #0 invalid per syntax]; nested exception is javax.naming.directory.InvalidAttributeValueException: [LDAP: error code 21 - sn: value #0 invalid per syntax]; remaining name 'uid=test,o=university.example.org'`

Now that these fields are required, their presence should be checked in the same place as the presence of the mail attribute is checked.

**Comment by oharsta** [comment]
Implemented in 4622450cb8665749c15ac3edf5eef40ab5d00ce4. Release https://build.surfconext.nl/repository/public/releases/org/surfnet/coin/coin-teams-war/4.2.12/

**Comment by oharsta** [comment]
Extra commit: d4040f3aaab1ab943788c88f2e1709dc157471ef
