### ISSUE TITLE
Add institutional groups to Teams

### ISSUE THREAD

**Issue by arnoutt** [OpenConext/OpenConext-teams#30]
As a user, my local institutional group management tool (such as GroupHub, LDAP, or a custom built tool) doesn't allow me to add 'external identities' to a group. External identities can be either guest users or students/teachers/researchers/employees from other institutions. In any case, they are _not_ visible in my local group management tool since they don't have an account from my institution. But sometimes I cooperate with those users in, for example, a project group. The project group already exists in my local group management tool, but without the external users. I therefore need another tool, such as SURFconext Teams, because those external users are indeed known within that tool. I therefore need a way to import my institutional groups into SURFconext Teams, and then add more users to it. To do this, I should be able to create a new group that uses the existing group as a basis (all members in that group are also automatically member of the newly created group) and then adding more members to it, through SURFconext Teams. Any service connected to SURFconext that queries the VOOT environment "show me all groups person X is member of" should also receive the newly created group.

Note that I should not be able to edit members of the institutional groups in SURFconext Teams; it should be read-only. Also, if membership changes within the institutional group (e.g. a member gets deleted), the query to the SURFconext VOOT environment must show this immediately. Finally, I should obviously only see my own institution's groups, not those of other institutions.

**Comment by thijskh** [comment]
To make it even more concrete:

Teams:
- User can create groups in OpenConext Teams that contain at most 1 existing group from their external group provider and additionally random people invited via the normal Teams process.
- User cannot see members of this external group. It's just displayed as the group name in the Teams interface, next to the individual Teams-based members.

Voot:
- SP can query all groups for a user, in which this group must be included if the user is either in the external group or in the bucket of invited users.
- Same when SP queries whether the user is in this group.
- If the user is not part of the org the external provider belongs to, it needs not be queried.
- There's no requirement to be able to get the list of members of this supergroup.

**Comment by maartenk** [comment]
@arnoutt @thijskh : Teams: At most or At least one group. 
I'm fine with at most for know, given the known usecase, but i wouldn't be surprised of ppl who would like to combine several groups into 1 supergroup.

**Comment by arnoutt** [comment]
@maartenk At most, for now. Other enhancements will follow :)

**Comment by thijskh** [comment]
We've decided on "at most" for now to keep the scope limited.

**Comment by thijskh** [comment]
Fixed in 4.2.14
