### ISSUE TITLE
Teams doesn't start if hostname can't be resolved

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-teams#31]
When deploying a fresh instance based on the templates, teams doesn't start because it can't resolve the local hostname:

```
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.classic.pattern.SyslogStartConverter@17b5b554 - Could not determine local host name java.net.UnknownHostException: ozconext-java: ozconext-java: Name or service not known
```

Of course, this is sloppy configuration of the host (in this case an Openstack instance based on the official Centos image), but I can't see why Teams wants to resolve the local hostname in the first place.  It just needs to listen on a port specified in the config, and that's it.

**Comment by thijskh** [comment]
This error is from the logging library: http://logback.qos.ch/xref/ch/qos/logback/classic/pattern/SyslogStartConverter.html#L91. It seems it requires this in order to be able to log to syslog. Doesn't seem there's an easy way to prevent that without patching the library.

**Comment by baszoetekouw** [comment]
Ok, maybe it's best then to add an explicit check in the common role to see if ```hostname --fqdn``` works correctly.
If the machine is misconfigured, it will then al teast result in an explicit error message.

**Comment by thijskh** [comment]
This check has been added in the deploy scripts. I believe that's enough for now.
